name: DeathSwap
version: ${project.version}
main: me.pzdrs.deathswap.DeathSwap
api-version: 1.13
authors: [Pzdrs]
description: DeathSwap plugin

commands:
  deathSwap:
    usage: /<command> <start|stop>
    aliases:
      - ds
